- name: Install Python and pip
  hosts: all
  become: true
  tasks:
    - name: Install Python
      ansible.builtin.apt:
        name: python3
        state: present
        update_cache: true

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Verify Python installation
      ansible.builtin.command: python3 --version
      register: python_version
      changed_when: false

    - name: Verify Pip installation
      ansible.builtin.command: pip3 --version
      register: pip_version
      changed_when: false

    - name: Print versions
      ansible.builtin.debug:
        msg: >
          {
            "python": "{{ python_version.stdout if python_version.rc == 0 else 'Not installed' }}",
            "pip": "{{ pip_version.stdout if pip_version.rc == 0 else 'Not installed' }}"
          }
