- name: Install Python and pip
  hosts: all
  become: true
  tasks:
    - name: Install Python
      apt:
        name: python3
        state: present
        update_cache: true

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Verify Python installation
      command: python3 --version
      register: python_version

    - name: Verify Pip installation
      command: pip3 --version
      register: pip_version

    - name: Print versions
      debug:
        msg: >
          {
            "python": "{{ python_version.stdout if python_version.rc == 0 else 'Not installed' }}",
            "pip": "{{ pip_version.stdout if pip_version.rc == 0 else 'Not installed' }}"
          }
