name: Terraform validate

on:
  push:
    branches:
      - "*"

jobs:
  validate:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform/

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true   

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color
