name: Terraform validate

on:
  push:
    branches:
      - "*"

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      - name: Terraform init
        run: terraform init
        working-directory: terraform/

      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/
